# Generated by Django 2.2.12 on 2023-04-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
    ]
